development:
  host: localhost
  database: bonnie-development

test:
  host: <%= ENV['TEST_DB_HOST'] || 'localhost' %>
  database: bonnie-test

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] || localhost %>
  port: <%= ENV['MONGOID_PORT'] || 27017 %>
  database: <%= ENV['MONGOID_DATABASE'] %>  
  <% if (ENV['MONGOID_USERNAME']) %>username: <%= ENV['MONGOID_USERNAME'] %><% end %>
  <% if (ENV['MONGOID_PASSWORD']) %>password: <%= ENV['MONGOID_PASSWORD'] %><% end %>
