development:
  sessions:
    default:
      database: bonnie-development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: bonnie-test
      hosts:
        - <%= ENV['TEST_DB_HOST'] || 'localhost' %>:27017

production:
  sessions:
    default:
      database: <%= ENV['MONGOID_DATABASE'] || 'bonnie-production' %>
      <% if (ENV['MONGOID_USERNAME']) %>username: <%= ENV['MONGOID_USERNAME'] %><% end %>
      <% if (ENV['MONGOID_PASSWORD']) %>password: <%= ENV['MONGOID_PASSWORD'] %><% end %>
      hosts:
        - <%= ENV['MONGOID_HOST'] || 'localhost' %>:<%= ENV['MONGOID_PORT'] || 27017 %>
